### PR TITLE
Unsupported Browser bypass

### PR DESCRIPTION
**Pull request by bdunlap**
Here's a more permanent fix for Shopify's 'unsupported browser' warning. Not sure if updating the user-agent string even does anything but calling the bypass URL seems to work for me.

### CODE REVIEW

**Comment by MartinAmps** [comment]
Hi Ben, thanks for the PR!

It looks like there's a syntax error here, you're missing a closing curly brace for the `browserBypass()` function.

Couple of other questions:

1) Do we need to make two HTTP requests here? can we modify the initial request with the browser bypass endpoint?

2) Can you switch from spaces to tabs to keep inline with the rest of the file?

Thanks again

Martin

**Comment by myjanky** [comment]
Thanks @bdunlap 
I reported this issue on april fools day with a proposed work around.
https://github.com/MartinAmps/Shopify-Private-APIs/issues/8#issuecomment-204555702

I see you did a commit with better code and I appreciate that.

**Comment by bdunlap** [comment]
OK I fixed the syntax error and I think the whitespace should be correct now. Sorry -- my dev machine is running php 5.3 (old array-literal syntax) so this is a little clunky on my end.

Without experimenting I don't know if this can be collapsed down into one HTTP request. Seems unlikely off the top of my head, though, since we need to do two things: (1) POST the login credentials, and (2) fetch the browser_bypass URL

**Comment by MartinAmps** [comment]
Only 18 months late ;)

**Pull request merged**
